set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${PROJECT_SOURCE_DIR}/virup/cmake/modules)

set(OCTREE_INCLUDE_DIR $ENV{OCTREE_INCLUDE_DIR})
set(OCTREE_LIBRARY $ENV{OCTREE_LIBRARY})

if((NOT DEFINED OCTREE_INCLUDE_DIR) OR (NOT DEFINED OCTREE_LIBRARY))
       find_package(Octree REQUIRED)
endif()
set(PROJECT_INCLUDE_DIRS ${OCTREE_INCLUDE_DIR})
set(PROJECT_LIBRARIES ${OCTREE_LIBRARY})
